### ISSUE TITLE
USB-C and USB 3.1 Ports on the Motherboard doesn't work (MSI B250 Gaming Pro Carbon)

### ISSUE THREAD

**Issue by TaroballzChen** [AurelienAudero/i5-7400-EFI-by-Aure#1]
I have an issue about B250 gaming pro carbon

there is a type-c interface behind MB ， the type-c is still working on your case ?

and how about USB3.1 beside the type-c ?

this two interface  didn't work for my case...

**Comment by AurelienAudero** [comment]
Hi,

## My conclusion

After a little bit of test,
| Port Number | Status                                                                                          |
|--------------|------------------------------------------------------------|
| 1                     | Working (here is my Bluetooth USB adapter)                          |
| 2                    | Working (I test it with a Samsung USB-A to USB-C adapter) |
| 3                    | Working                                                                                        |
| 4                    | Working                                                                                        |

I tested all the ports with a 32GB USB 3.0 Stick and with my bluetooth adapter for the port n°1

![USB-Port-Numerotation](https://user-images.githubusercontent.com/64486562/121818708-1cc21780-cc89-11eb-93d4-b9f8d733d208.png)

## My Questions

- With what device are you testing the ports ?
- What is the specific ports where it doesn't work (give me the number(s) with the picture above)
- Is it working a little bit or not working at all ?

**Comment by TaroballzChen** [comment]
I'm sorry for that I was late for providing my solution 

- update opencore to the newest verision (v0.7.0) and transfer config.plist to the new one
- remove my old EC.aml  and download the prebuilt [EC-USBX.aml](https://github.com/dortania/Getting-Started-With-ACPI/blob/master/extra-files/compiled/SSDT-EC-USBX-DESKTOP.aml) which the opencore install guide provided 
- update bigsur to the newest version(11.4)
- all usb and typec port working well..
