### ISSUE TITLE
[Question] Thanks you

### ISSUE THREAD

**Issue by uzmi** [AurelienAudero/i5-7400-EFI-by-Aure#13]
### What is your question ?

Hi there! Thank you so much for sharing data. I'm using it in my processor and it's perefectly working.
Regards

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AurelienAudero** [comment]
Hi @uzmi
I'm glad my EFI is working perfectly for you.

If you like my work, you can leave a star on this repository.
You can also turn on the notification bell to don't miss when updates are available.

Thanks for using my EFI
Have a great day
