### ISSUE TITLE
[Question] Disk not showing in macOS Ventura installer

### ISSUE THREAD

**Issue by fayyaz42** [AurelienAudero/i5-7400-EFI-by-Aure#16]
### What is your question ?

For installation Ventura No Disk is shown only install USB is shown
install usb works fine
when install Ventura page appears No Disk is recognized only install usb appears
Disk utility also not showing any Disk

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AurelienAudero** [comment]
Hi @fayyaz42,
**You posted this message in the wrong category.**

I encourage you to repost this message by clicking [here](https://github.com/AurelienAudero/Intel-i5-7400-Hackintosh-EFI/issues/new/choose) and choosing "Bug Report" in the language of your choice.
This will allow me to have more informations that will help me solve your problem and it will also help other people in the future who could encounter the same problem.
After that, I would be happy to help you solve your issue.

Thanks for using my EFI.
Aurélien
