### ISSUE TITLE
[Question] Intel HD Graphics 630 only shows 3MB

### ISSUE THREAD

**Issue by ghost** [AurelienAudero/i5-7400-EFI-by-Aure#18]
### What is your question ?

ola would like to know how to fix the memory of intel hd grafics 630, in my shows that has 3mb and keeps locking

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AurelienAudero** [comment]
Hi @Clebersp,
Is your motherboard a H110 ?

Thanks for using my EFI.
Aurélien

**Comment by AurelienAudero** [comment]
Hi @Clebersp,
Since this issue has been inactive for a while now, I will close it now.
If you need help, I invite you to open a new issue by clicking [here](https://github.com/AurelienAudero/Intel-i5-7400-Hackintosh-EFI/issues/new/choose).

Thanks.
Aurélien.
