### ISSUE TITLE
[Bug] Endless load screen

### ISSUE THREAD

**Issue by adomerle** [AurelienAudero/i5-7400-EFI-by-Aure#28]
### What is your configuration ?

- CPU: i5-7400
- Motherboard: MSI H110M PRO-VH PLUS
- RAM: 16GB
- Hard Disk: 512GB nvme ssd
- GPU: Intel HD Graphics 630
- Additional infos:
Continuation of issue #12
CFG Lock disabled

### Describe the Bug

I have the same problem as in https://github.com/AurelienAudero/Intel-i5-7400-Hackintosh-EFI/issues/12#issuecomment-1484679182 Originally posted by @caicatar
I'm using the v3.02 EFI.

### Steps to Reproduce

1. I boot to OpenCore
2. I select Install macOS Sonoma

### I'm checking my form

- [X] I have specified a title related to my problem
- [X] My title starts with "[Bug]" (without the quotes)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AurelienAudero** [comment]
Hi @adomerle,
As said in the issue #12, your issue appears to be iGPU related.

- Can you try this [modified EFI](https://github.com/AurelienAudero/Intel-i5-7400-Hackintosh-EFI/files/12833327/Intel_i5-7400_Hackintosh_EFI_DEBUG_Issue28-v1.zip) and give me a feedback ?
- If the issue persists, please send me a picture of the entire screen showing the Kernel Panic or the verbose output

Thanks for using my EFI.
Aurélien.

> **⚠️ NOTE AND WARNINGS :**
> - **Please note that this modified EFI is only a test version !** _If it works, a definitive and more polished version will be available in [the Release section](https://github.com/AurelienAudero/Intel-i5-7400-Hackintosh-EFI/releases) fo this repository._
> - This modified version of the EFI is based on [the latest version of the EFI (with boot picker) at that time (v3.02)](https://github.com/AurelienAudero/Intel-i5-7400-Hackintosh-EFI/releases/tag/3.02). This should be compatible with the stable release of macOS Sonoma 14.0. **The compatibility of macOS Beta Softwares are not guaranteed.**
> - This EFI already contains all the necessary SMBIOS informations to boot, theses informations have been generated according to [this part of the installation guide](https://github.com/AurelienAudero/Intel-i5-7400-Hackintosh-EFI#setup-the-smbios). **It's strongly recommended to generate your own SMBIOS once your issue has been resolved. You should never share your personal SMBIOS !**

**Comment by adomerle** [comment]
@AurelienAudero Thanks! That modifed EFI solved issue.

**Comment by AurelienAudero** [comment]
@adomerle Can you please test with [this new modified EFI](https://github.com/AurelienAudero/Intel-i5-7400-Hackintosh-EFI/files/12834180/Intel_i5-7400_Hackintosh_EFI_DEBUG_Issue28-v2.zip) ? Does it still work ?
Can you confirm that graphics acceleration is working ? (Transparent dock, About this Mac showing more than 3MB, …)

> **⚠️ NOTE AND WARNINGS :**
> - **Please note that this modified EFI is only a test version !** _If it works, a definitive and more polished version will be available in [the Release section](https://github.com/AurelienAudero/Intel-i5-7400-Hackintosh-EFI/releases) fo this repository._
> - This modified version of the EFI is based on [the latest version of the EFI (without boot picker) at that time (v3.02)](https://github.com/AurelienAudero/Intel-i5-7400-Hackintosh-EFI/releases/tag/3.02). This should be compatible with the stable release of macOS Sonoma 14.0. **The compatibility of macOS Beta Softwares are not guaranteed.**
> - This EFI already contains all the necessary SMBIOS informations to boot, theses informations have been generated according to [this part of the installation guide](https://github.com/AurelienAudero/Intel-i5-7400-Hackintosh-EFI#setup-the-smbios). **It's strongly recommended to generate your own SMBIOS once your issue has been resolved. You should never share your personal SMBIOS !**
> - To show the boot picker, hold the `Option`/`Alt` key at startup

**Comment by adomerle** [comment]
@AurelienAudero glitches appeared + it hangs
![photo_2023-10-06_22-44-46](https://github.com/AurelienAudero/Intel-i5-7400-Hackintosh-EFI/assets/147173510/4b2acedd-91fc-4446-88e5-5d30829c89b4)

**Comment by AurelienAudero** [comment]
@adomerle And it worked well with the first version ?

**Comment by adomerle** [comment]
> @adomerle And it worked well with the first version ?

Yes, rebooted to the first version, works fine
![Screenshot_20231006_225042](https://github.com/AurelienAudero/Intel-i5-7400-Hackintosh-EFI/assets/147173510/04b8ae4f-41c6-46ce-b892-01c48c1d916d)

**Comment by AurelienAudero** [comment]
@adomerle Okay, thanks. Can you give a try to [this one](https://github.com/AurelienAudero/Intel-i5-7400-Hackintosh-EFI/files/12834656/Intel_i5-7400_Hackintosh_EFI_DEBUG_Issue28-v3.zip) ?
I'm trying to get the most polished version possible in order to release an update.

> **⚠️ NOTE AND WARNINGS :**
> - **Please note that this modified EFI is only a test version !** _If it works, a definitive and more polished version will be available in [the Release section](https://github.com/AurelienAudero/Intel-i5-7400-Hackintosh-EFI/releases) fo this repository._
> - This modified version of the EFI is based on [the latest version of the EFI (without boot picker) at that time (v3.02)](https://github.com/AurelienAudero/Intel-i5-7400-Hackintosh-EFI/releases/tag/3.02). This should be compatible with the stable release of macOS Sonoma 14.0. **The compatibility of macOS Beta Softwares are not guaranteed.**
> - This EFI already contains all the necessary SMBIOS informations to boot, theses informations have been generated according to [this part of the installation guide](https://github.com/AurelienAudero/Intel-i5-7400-Hackintosh-EFI#setup-the-smbios). **It's strongly recommended to generate your own SMBIOS once your issue has been resolved. You should never share your personal SMBIOS !**
> - To show the boot picker, hold the `Option`/`Alt` key at startup

**Comment by adomerle** [comment]
@AurelienAudero same glitches

**Comment by AurelienAudero** [comment]
@adomerle I think a found what caused the issue. Can you give a final try to [this one](https://github.com/AurelienAudero/Intel-i5-7400-Hackintosh-EFI/files/12834824/Intel_i5-7400_Hackintosh_EFI_DEBUG_Issue28-v4.zip) ?

Thanks for your time.
Aurélien.

> **⚠️ NOTE AND WARNINGS :**
> - **Please note that this modified EFI is only a test version !** _If it works, a definitive and more polished version will be available in [the Release section](https://github.com/AurelienAudero/Intel-i5-7400-Hackintosh-EFI/releases) fo this repository._
> - This modified version of the EFI is based on [the latest version of the EFI (without boot picker) at that time (v3.02)](https://github.com/AurelienAudero/Intel-i5-7400-Hackintosh-EFI/releases/tag/3.02). This should be compatible with the stable release of macOS Sonoma 14.0. **The compatibility of macOS Beta Softwares are not guaranteed.**
> - This EFI already contains all the necessary SMBIOS informations to boot, theses informations have been generated according to [this part of the installation guide](https://github.com/AurelienAudero/Intel-i5-7400-Hackintosh-EFI#setup-the-smbios). **It's strongly recommended to generate your own SMBIOS once your issue has been resolved. You should never share your personal SMBIOS !**
> - To show the boot picker, hold the `Option`/`Alt` key at startup

**Comment by AurelienAudero** [comment]
@adomerle I think a found what caused the issue. Can you give a final try to [this one](https://github.com/AurelienAudero/Intel-i5-7400-Hackintosh-EFI/files/12834842/Intel_i5-7400_Hackintosh_EFI_DEBUG_Issue28-v4.zip) ?

Thanks for your time.
Aurélien.

> **⚠️ NOTE AND WARNINGS :**
> - **Please note that this modified EFI is only a test version !** _If it works, a definitive and more polished version will be available in [the Release section](https://github.com/AurelienAudero/Intel-i5-7400-Hackintosh-EFI/releases) fo this repository._
> - This modified version of the EFI is based on [the latest version of the EFI (without boot picker) at that time (v3.02)](https://github.com/AurelienAudero/Intel-i5-7400-Hackintosh-EFI/releases/tag/3.02). This should be compatible with the stable release of macOS Sonoma 14.0. **The compatibility of macOS Beta Softwares are not guaranteed.**
> - This EFI already contains all the necessary SMBIOS informations to boot, theses informations have been generated according to [this part of the installation guide](https://github.com/AurelienAudero/Intel-i5-7400-Hackintosh-EFI#setup-the-smbios). **It's strongly recommended to generate your own SMBIOS once your issue has been resolved. You should never share your personal SMBIOS !**
> - To show the boot picker, hold the `Option`/`Alt` key at startup

**Comment by adomerle** [comment]
@AurelienAudero Yes, the latest debug efi works fine

**Comment by AurelienAudero** [comment]
@adomerle Thanks a lot for your feedback. [The new v3.03 version](https://github.com/AurelienAudero/Intel-i5-7400-Hackintosh-EFI/tree/3.03) is now live.
I invite you to update to this version and generate your own SMBIOS by following [these instructions](https://github.com/AurelienAudero/Intel-i5-7400-Hackintosh-EFI#setup-the-smbios), if it's not already done.

I will now close this issue as it has been resolved.

Thanks again for your time.
Aurélien
