### ISSUE TITLE
[Question] Issue when booting into installer display stops outputting

### ISSUE THREAD

**Issue by ryano365** [AurelienAudero/i5-7400-EFI-by-Aure#40]
### What is your question ?

Hey there, 

Sorry to bother you im just looking to see if I can get some help understanding what is going on with my install.
When booting into the mac oc installer I see the apple logo and the progress bar at the bottom, As this bar begins to progress the video output stops and subsequently the monitor goes to sleep. I have set the DVMT Pre-Allocated memory in the bios to 128mb as suggested  but I just cant seem to get past this stage,

Any help would be greatly appreciated I can supply more information as it will be probably be needed for someone to help me im just not sure what to provide at the moment. The configuration is nearly identical to whats listed on the guide cpu and ig being the same.

Thanks for your time.

### I'm checking my form

- [X] My question is not about a bug or issue I have using this EFI (if so, I use the form named "Bug/Issue Report")
- [X] I have specified a title related to my problem
- [X] My title starts with "[Question]" (without the quotes)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AurelienAudero** [comment]
Hi @ryano365,
Sorry for the late answer, I had a lot of work to do lately.
What you are talking about here is not a question and should be classified as a bug.
As the question form doesn't give me the necessary informations to help you, I invite you to recreate another issue using the correct form this time (Select the `Bug/Issue Report` in your preferred language on [this page](https://github.com/AurelienAudero/Intel-i5-7400-Hackintosh-EFI/issues/new/choose)).

Thanks for using my EFI.
Aurélien.
